apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: Workflows-Quickstart
  title: Create a New GitHub Repository
  description: Creates a new GitHub Repository 
spec:
  owner: john.crespo@harness.io
  type: service
  parameters:
    - title: Fill in the repo details
      required:
        - github_org_name
        - github_repo_name
        - github_username
      properties:
        github_org_name:
          title: Provide your GitHub Organization
          type: string
          description: Name the org where you want to add the new repository
        github_repo_name:
          title: Provide your repository Location
          type: string
          description: Name the new repository that you want to create 
        github_username:
          title: Provide your GitHub Username
          type: string
          description: Add Your GitHub Username 
        token:
          title: Harness Token
          type: string
          ui:widget: password
          ui:field: HarnessAuthToken  
  steps:
    - id: trigger
      name: Onboarding a New GitHub Repository
      action: trigger:harness-custom-pipeline
      input:
        url: "https://app.harness.io/ng/account/SAsyUUHTTImuYSZ35HPDvw/module/idp-admin/orgs/default/projects/jcproject/pipelines/Github_Repo_Onboarding/pipeline-studio?storeType=INLINE&stageId=IDP&sectionId=EXECUTION"
        inputset:
          github_org: ${{ parameters.github_org_name }}
          github_repo: ${{ parameters.github_repo_name }}
          github_username: ${{parameters.github_username}}
        apikey: ${{ parameters.token }}
  output:
    links:
      - title: Pipeline Details
        url: ${{ steps.trigger.output.PipelineUrl }}
